### ISSUE TITLE
Integration with nvim-notify

### ISSUE THREAD

**Issue by sheepy9** [vilari-mickopf/praise-the-run.nvim#1]
Since the plugin can also handle compilation of projects, which can be a longer task, it would be really cool to have integration with nvim-notify, to get asynchronous notifications about the success/fail status of the main run command.

**Comment by vilari-mickopf** [comment]
Patches are welcome

**Comment by sheepy9** [comment]
It is obvious that our vision for this plugin is too different to be contained in one project. I am afraid this is where our collaboration ends. I will be forking this project so that I can make it gloriously incandescent.

**Comment by vilari-mickopf** [comment]
Gl
